import React from 'react';
import {
  Home,
  Overview,
  Mission,
  Leadership,
  BioReactors,
  Fermenters,
  CIPStations,
  VaporizationVessel,
  ProcessVessel,
  MobileVessel,
  BufferVessel,
  HarvestVessel,
  MediaVessel,
  CIPSIPSkids,
  FiltrationSkids,
  InactivationVessel,
  MixingTanks,
  AutomationSolutions,
  Clientele,
  Gallery,
  Services,
  Contact,
} from './pages';

export const RoutesElements = [
  { path: '/', element: <Home /> },
  { path: '/about', element: <Overview /> },
  { path: '/about/mission', element: <Mission /> },
  { path: '/about/leadership', element: <Leadership /> },
  { path: '/products/bioreactors', element: <BioReactors /> },
  { path: '/products/fermenters', element: <Fermenters /> },
  { path: '/products/cip-stations', element: <CIPStations /> },
  { path: '/products/vaporization-vessel', element: <VaporizationVessel /> },
  { path: '/products/process-vessel', element: <ProcessVessel /> },
  { path: '/products/mobile-vessel', element: <MobileVessel /> },
  { path: '/products/buffer-vessel', element: <BufferVessel /> },
  { path: '/products/harvest-vessel', element: <HarvestVessel /> },
  { path: '/products/media-vessel', element: <MediaVessel /> },
  { path: '/products/cip-sip-skids', element: <CIPSIPSkids /> },
  { path: '/products/filtration-skids', element: <FiltrationSkids /> },
  { path: '/products/inactivation-vessel', element: <InactivationVessel /> },
  { path: '/products/mixing-tanks', element: <MixingTanks /> },
  { path: '/products/automation-solutions', element: <AutomationSolutions /> },
  { path: '/clientele', element: <Clientele /> },
  { path: '/gallery', element: <Gallery /> },
  { path: '/services', element: <Services /> },
  { path: '/contact', element: <Contact /> },
];
